"""Regenerate template.yaml and lease.asl.json from microvm-ctl's state machine generator.

    pip install microvm-ctl
    python3 generate.py [--budget 300] [--heartbeat 90] [--heartbeat-every 30]

`lease.asl.json` is the plain state machine (placeholder account, region, and role) for
reading; it is what `mvm lease asl --image handoff-agent --execution-role <arn> --budget 300
--heartbeat 90` prints. `template.yaml` inlines the same machine as `DefinitionString: !Sub`
with `${ImageName}`, `${AgentExecutionRole.Arn}`, `${AWS::Region}`, and `${Budget}` in place
of the literals. JSONata expressions use `{% %}` and `$name`, never `${`, so `Fn::Sub` leaves
them alone; this script checks that before writing.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
from pathlib import Path

from microvm.integrations.stepfunctions import lease_state_machine
from microvm.lease import LeasePolicy

HERE = Path(__file__).parent
SLACK_S = 120  # the VM outlives the budget by this much, no more
PLACEHOLDER_ACCOUNT = "123456789012"
PLACEHOLDER_REGION = "us-east-1"
SUB_NAMES = {"ImageName", "AgentExecutionRole.Arn", "AWS::Region", "AWS::AccountId", "AWS::StackName",
             "Budget"}
BUDGET_SENTINEL = "__BUDGET__"


def plain_asl(image: str, budget: int, heartbeat: int, every: int) -> dict:
    """The committed lease.asl.json: concrete placeholder ARNs, nothing to substitute."""
    return lease_state_machine(
        image_arn=f"arn:aws:lambda:{PLACEHOLDER_REGION}:{PLACEHOLDER_ACCOUNT}:microvm-image:{image}",
        execution_role_arn=f"arn:aws:iam::{PLACEHOLDER_ACCOUNT}:role/microvm-sfn-handoff-agent",
        policy=LeasePolicy(budget_s=budget, heartbeat_timeout_s=heartbeat, slack_s=SLACK_S),
        region=PLACEHOLDER_REGION, heartbeat_s=every,
    )


def parameterised_asl(budget: int, heartbeat: int, every: int) -> str:
    """The DefinitionString body: the same machine with CloudFormation placeholders.

    Budget-derived numbers cannot be computed by Fn::Sub, so TimeoutSeconds and the idle
    cap take `${Budget}` literally and the two derived values become JSONata arithmetic."""
    asl = lease_state_machine(
        image_arn="arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:microvm-image:${ImageName}",
        execution_role_arn="${AgentExecutionRole.Arn}",
        policy=LeasePolicy(budget_s=budget, heartbeat_timeout_s=heartbeat, slack_s=SLACK_S),
        region="${AWS::Region}", heartbeat_s=every,
    )
    asl = copy.deepcopy(asl)
    asl["Comment"] = (f"microvm-ctl lease of ${{ImageName}}: budget ${{Budget}}s, VM cap "
                      f"Budget + {SLACK_S}s (generated by generate.py, do not edit by hand)")
    lease = asl["States"]["Lease"]
    lease["TimeoutSeconds"] = BUDGET_SENTINEL
    lease["Arguments"]["IdlePolicy"]["MaxIdleDurationSeconds"] = BUDGET_SENTINEL
    lease["Arguments"]["MaximumDurationInSeconds"] = f"{{% ${{Budget}} + {SLACK_S} %}}"
    stale = asl["States"]["TerminateStale"]
    stale_ms = (budget + SLACK_S) * 1000
    assert f"- {stale_ms}]]" in stale["Items"], stale["Items"]
    stale["Items"] = stale["Items"].replace(f"- {stale_ms}]]", f"- (${{Budget}} + {SLACK_S}) * 1000]]")
    text = json.dumps(asl, indent=2).replace(f'"{BUDGET_SENTINEL}"', "${Budget}")
    found = set(re.findall(r"\$\{([^}]*)\}", text))
    unexpected = found - SUB_NAMES
    if unexpected:
        raise SystemExit(f"DefinitionString has ${{...}} that Fn::Sub would mangle: {sorted(unexpected)}")
    return text


TEMPLATE = """\
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Step Functions state machine that leases a Lambda MicroVM (built with microvm-ctl) to one
  task with runMicrovm.waitForTaskToken and lets the VM complete the task token itself.
  Generated by generate.py from microvm.integrations.stepfunctions; do not edit by hand.

Parameters:
  ImageName:
    Type: String
    Default: handoff-agent
    Description: Name of the agent MicroVM image built with `mvm image build`.
  Budget:
    Type: Number
    Default: {budget}
    Description: Seconds the state machine waits for the VM (TimeoutSeconds); the VM cap is Budget + {slack}.

Resources:
  # ---- the role the leased VM runs as: logs on both group prefixes, task token calls back to this machine
  AgentExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${{AWS::StackName}}-agent
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {{ Service: lambda.amazonaws.com }}
            Action: [sts:AssumeRole, sts:TagSession]
      Policies:
        - PolicyName: agent
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents]
                Resource:
                  - !Sub arn:aws:logs:${{AWS::Region}}:${{AWS::AccountId}}:log-group:/aws/lambda-microvms/*
                  - !Sub arn:aws:logs:${{AWS::Region}}:${{AWS::AccountId}}:log-group:/aws/lambda/microvms/*
              - Sid: CompleteTheLease
                Effect: Allow
                Action: [states:SendTaskSuccess, states:SendTaskFailure, states:SendTaskHeartbeat]
                # the machine is named below so this ARN is known before it exists (no circular reference)
                Resource: !Sub arn:aws:states:${{AWS::Region}}:${{AWS::AccountId}}:stateMachine:${{AWS::StackName}}-lease

  # ---- the role the state machine runs as: launch, list, terminate, and pass the agent role
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${{AWS::StackName}}-states
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {{ Service: states.amazonaws.com }}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: orchestrator
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [lambda:RunMicrovm, lambda:TerminateMicrovm, lambda:ListMicrovms, lambda:GetMicrovm]
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt AgentExecutionRole.Arn
              - Effect: Allow
                Action: lambda:PassNetworkConnector
                Resource: arn:aws:lambda:*:aws:network-connector:aws-network-connector:*

  # ---- Lease (waitForTaskToken) -> Terminate -> Done; timeouts and failures -> Reap -> TerminateStale -> Failed
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${{AWS::StackName}}-lease
      StateMachineType: STANDARD
      RoleArn: !GetAtt StateMachineRole.Arn
      DefinitionString: !Sub |
{definition}

Outputs:
  StateMachineArn:
    Value: !Ref StateMachine
    Description: Start executions here; run.sh reads it from the stack.
  AgentExecutionRoleArn:
    Value: !GetAtt AgentExecutionRole.Arn
    Description: Pass as MVM_EXECUTION_ROLE_ARN when leasing the agent image by hand.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", default="handoff-agent")
    ap.add_argument("--budget", type=int, default=300,
                    help="seconds the state machine waits (TimeoutSeconds)")
    ap.add_argument("--heartbeat", type=int, default=90,
                    help="heartbeat timeout in seconds (HeartbeatSeconds)")
    ap.add_argument("--heartbeat-every", type=int, default=30, help="seconds between VM heartbeats")
    args = ap.parse_args()

    asl_path = HERE / "lease.asl.json"
    asl_path.write_text(json.dumps(plain_asl(args.image, args.budget, args.heartbeat, args.heartbeat_every),
                                   indent=2) + "\n")
    definition = parameterised_asl(args.budget, args.heartbeat, args.heartbeat_every)
    body = "\n".join(f"        {line}" if line else "" for line in definition.splitlines())
    (HERE / "template.yaml").write_text(TEMPLATE.format(budget=args.budget, slack=SLACK_S, definition=body))
    print(f"wrote {asl_path.name} and template.yaml "
          f"(budget {args.budget}s, heartbeat timeout {args.heartbeat}s)")


if __name__ == "__main__":
    main()
